services:
  app:
    build:
      context: ./frontend
      target: prod
    ports:
      - 3000:80
    volumes:
      - ./frontend:/frontend
  api:
    build:
      context: ./backend
      target: prod
    ports:
      - 8000:8000
    volumes:
      - ./backend:/backend
  db:
    image: postgres:16-alpine
    volumes:
      - postgres-db:/var/lib/postgresql/data/
    environment:
      - "POSTGRES_HOST_AUTH_METHOD=trust"

volumes:
  postgres-db: