services:
  app:
    build:
      context: ./frontend
      target: prod
    ports:
      - 3000:80
    volumes:
      - ./frontend:/frontend
  api:
    build:
      context: ./backend
      target: prod
    ports:
      - 8000:8000
    volumes:
      - ./backend:/backend